### ISSUE TITLE
Set-up page

### ISSUE THREAD

**Issue by ldickson** [rgauci/Track#2]
On the free text question when I click to type an answer the space for the free text disappears so I can't see the full letters when I'm typing.

**Comment by rgauci** [comment]
Can you provide a screenshot of this, please?
(I can't replicate it on my devices since I have bigger screens.)

**Comment by rgauci** [comment]
![screenshot_2015-07-18-14-48-24](https://cloud.githubusercontent.com/assets/1950367/8762344/9185f7dc-2d6e-11e5-8982-890e4e4f177e.png)

**Comment by rgauci** [comment]
This should be fixed with the latest update, feel free to re-open this issue if not.
