### ISSUE TITLE
Sampling timeframe

### ISSUE THREAD

**Issue by ldickson** [rgauci/Track#4]
Would it be possible to have the sampling run from the hours 7.30am-10.30pm but be split into 3 hour blocks (7.30am-10.30am; 10.30am-1.30pm; 1.30pm-4.30pm; 4.30pm-7.30pm; 7.30pm-10.30pm), so there would be 5 notifications each day?

I was also wondering if it would be possible to move the sampling window if required, for example I'm thinking if participants say that their typical waking hours are 9.30am-12.30am, to increase the chances of them completing all the esm notifications in a day?

**Comment by rgauci** [comment]
OK, I will schedule the "Random" notification as requested and change the default number of samples per day from 8 to 5.

Re moving the sampling window - this is already possible. If you click on Daily Start Time and Daily End Time, you can change the times as required. However as it is the validation will prevent you from going over to the next day (latest end time cannot be past midnight). Do you want this to be changed?

**Comment by rgauci** [comment]
Working on random scheduling. Here are a sample of notification times for a which have been generated randomly (these are generated during the Setup stage and will be different for every participant).

Sun, 19 Jul 2015, 07:56:02
Sun, 19 Jul 2015, 13:09:50
Sun, 19 Jul 2015, 15:18:30
Sun, 19 Jul 2015, 16:30:27
Sun, 19 Jul 2015, 21:20:39
Mon, 20 Jul 2015, 08:20:35
Mon, 20 Jul 2015, 11:22:16
Mon, 20 Jul 2015, 13:53:36
Mon, 20 Jul 2015, 18:37:58
Mon, 20 Jul 2015, 21:43:02
Tue, 21 Jul 2015, 08:16:14
Tue, 21 Jul 2015, 12:14:31
Tue, 21 Jul 2015, 16:06:24
Tue, 21 Jul 2015, 17:27:42
Tue, 21 Jul 2015, 20:53:15
Wed, 22 Jul 2015, 09:01:42
Wed, 22 Jul 2015, 11:05:46
Wed, 22 Jul 2015, 14:49:56
Wed, 22 Jul 2015, 18:26:42
Wed, 22 Jul 2015, 21:34:24
Thu, 23 Jul 2015, 10:29:52
Thu, 23 Jul 2015, 11:42:17
Thu, 23 Jul 2015, 15:50:49
Thu, 23 Jul 2015, 18:25:49
Thu, 23 Jul 2015, 19:55:42
Fri, 24 Jul 2015, 07:39:03
Fri, 24 Jul 2015, 11:46:19
Fri, 24 Jul 2015, 15:34:54
Fri, 24 Jul 2015, 17:31:11
Fri, 24 Jul 2015, 21:53:01

**Comment by ldickson** [comment]
If possible could the sampling window go past midnight? 

Had a quick look at random sampling schedule there - I think this looks good, will have another proper look at it now and let you know

**Comment by rgauci** [comment]
OK I'll do some changes to make it go past midnight.

**Comment by ldickson** [comment]
Thanks - random sampling looks good too :)
