### ISSUE TITLE
branching questions

### ISSUE THREAD

**Issue by ldickson** [rgauci/Track#5]
For the initial questions about emotions would it be possible to have these on individual screens as yes/no questions and then if the participant answers yes this would go on to the questions about regulation strategies?

**Comment by rgauci** [comment]
Sorry, I'm afraid I didn't understand that. Can you please clarify?

**Comment by ldickson** [comment]
No problem, could the questions that start 'right now I feel cheerful' etc be presented individually on a page so participants would see 'right now I feel cheerful' and would answer 'yes' or 'no' (rather than multiple choice) and then if they answer 'yes' this would take them to the pages that ask about the regulation strategies (e.g. 'how much are you.....)

**Comment by rgauci** [comment]
Let me see if I understand you correctly.
We start showing questions from 1 to 9 until they answer "Yes" to one of them.
Once they answer "Yes", we skip the remaining and go directly to 10.
So, for example:
- Right now I, feel cheerful. No.
- Right now, I feel satisfied. No.
- Right now, I feel enthusiastic. Yes.
- How much are you: thinking about a situation differently?
  ...

**Comment by ldickson** [comment]
That's pretty much it apart from if they answer yes to any of questions 1-9 they go to questions 10-15, but then back to questions 1-9 until they answer them all (i'm thinking that participants might experience 2 emotions at the same time but will be regulating them differently if that makes sense....)

**Comment by rgauci** [comment]
So, for example: 1 - 3, 10 - 15, 4 - 9.
What happens if they then answer 'Yes' to one of questions 4 - 9?

**Comment by ldickson** [comment]
Yeah, so then if they answered yes to any of 4-9 it would go back to 10-15
so for example;
Q1 No
Q2 Yes 
Q10-15
Q3 No
Q4 No
Q5 No
Q6 Yes 
Q10-15
Q7 No
Q8 No
Q9 No 
Q16 etc

**Comment by rgauci** [comment]
OK, got it! That'll be relatively easy to implement now that we have a configurable system in place. :)
Sorry for the many questions, I just really wanted to make sure I understood correctly.

**Comment by ldickson** [comment]
no worries at all! :) I just wanted to check if this will be up and running on the latest version of the app?

**Comment by rgauci** [comment]
Have you installed the latest version? Should be included.
