### ISSUE TITLE
Feedback module

### ISSUE THREAD

**Issue by ldickson** [rgauci/Track#8]
I'm having trouble getting to the feedback module - when I put in my password it's always coming up as invalid - I'm pretty sure it's the right one I'm putting in! I just wanted to flag this up before I do forgot password.

**Comment by rgauci** [comment]
Have you ever been able to access the feedback module? Or have you always gotten the invalid password message? (Trying to find the source of the problem.)

**Comment by ldickson** [comment]
I have accessed the feedback module before but not when we made the changes to the daily charts etc which I think was at the same time as the password was added....hope that helps

**Comment by rgauci** [comment]
Have you ever accessed the feedback module since you last installed the app?

**Comment by rgauci** [comment]
(It's hard to determine the source of the problem since I'm able to access the feedback module on mine.)

**Comment by rgauci** [comment]
I've had a look at the code and believe I've identified the source of the problem, should be an easy fix. I'll work on it and send you an update ASAP.

**Comment by ldickson** [comment]
Thank you :) I haven't been able to access it since the last update

**Comment by rgauci** [comment]
I've just sent you an update which I believe should fix this. I'm afraid you might still need to change your password (via the Forgot Password feature) for you to be able to log in. Following that, let me know if you experience this issue again.

**Comment by rgauci** [comment]
You won't be able to immediately view feedback once you change the password (you will need to complete 5 more surveys), but you can test the update as follows:
1. Update password via 'Forgot Password' screen.
   (You can use the same on you used previously, just make sure you re-save it from this screen.)
2. Go to the 'Change Password' screen.
3. Test password validation by entering text <b>only</b> in the 'Current Password' text box, as seen in the below screenshot.

The password validation on this screen is the same as that on the login screen, so you should be able to confirm that you do not get any 'Invalid password' messages when entering the correct (newly-reset) password.

![changepassword](https://cloud.githubusercontent.com/assets/1950367/9290431/3a2119bc-438b-11e5-9077-4c3db2de01d5.png)

**Comment by rgauci** [comment]
I’m sorry to hear that you're still experiencing the issue, and unfortunately can’t think of what’s causing it at the moment since I can’t replicate it on any of my devices. :(

Can you please confirm whether you are getting an ‘Invalid Password’ error message on <b>both</b> the feedback <i>Login</i> and <i>Change Password</i> screens?

Can you also please confirm that you are running version 1.2 of the app?
(You should be able to locate the App Info from your device's settings.)

**Comment by ldickson** [comment]
good news - I just checked this, really sorry but I have version 1.0 - I must of missed version 1.2 along the way - will try and update this now! :)

**Comment by ldickson** [comment]
I've updated the version and tested it out from the instructions above - I don't get the invalid password message again so hopefully that's it (sorry again for causing confusion with the version numbers!)

**Comment by rgauci** [comment]
No worries, there's been a lot emails going about! Do you need to fill out 5 more surveys before you are able to access the feedback module?

**Comment by ldickson** [comment]
Yup (although already had a notification so 4 to go!) :)

**Comment by rgauci** [comment]
Check your email, I've sent a temporary patch for testing. :)

**Comment by rgauci** [comment]
Hi Laura, I'm closing this thread following our e-mail discussion re the issue being resolved. Feel free to re-open if you experience it again.
